### ISSUE TITLE
Disponibilidade da captura dos Documentos

### ISSUE THREAD

**Issue by ricardorinco** [acesso-io/acessobio-webframe#1]
Olá **pessoal**,

Tudo bem?

Estou trabalhando em um projeto no qual a empresa é uma parceira da Acesso Digital, eu estou utilizando o _acessobio-webframe_ para que todos os parâmetros sejam seguido corretamente, porém não encontrei nada referente a um framework web para captura dos documentos. 

Eu verifiquei que esse framework está disponível para iOS e Android, porém como citado o projeto está sendo desenvolvido utilizando plataforma web.

Eu gostaria de saber se existe a possibilidade de disponibilização também do framework de Captura do Documentos?

Fico no aguardo

**Comment by lucas-ibiapina** [comment]
Olá @ricardorinco Ricardo, como vai?

Sim, está no nosso roadmap disponibilizar captura de documentos, estamos já disponibilizando a captura inteligente que usa IA no reconhecimento e enquadramento da face com captura automática que é uma funcionalidade que hoje já existe nas SDK's nativas iOS e Android.

Agradecemos pelo contato.

**Comment by ricardorinco** [comment]
Bom dia Lucas @lucas-ibiapina. estou bem e você?

Que boa notícia, vocês tem uma previsão de data para a disponibilização deste framework?

**Comment by lucas-ibiapina** [comment]
Olá @ricardorinco, poderia me passar seu e-mail e continuarmos a conversa por lá?

Abraços!

**Comment by ricardorinco** [comment]
Opa, claro, segue meu e-mail rickrinco.work@gmail.com.

Abraço
